import { subDays, formatISO } from "date-fns";
import type { CampaignPerformance, CampaignReport, CampaignSummary } from "./types";

function summarize(campaigns: CampaignPerformance[]): CampaignSummary {
  const recipients = campaigns.reduce((sum, c) => sum + c.recipients, 0);
  const delivered = campaigns.reduce((sum, c) => sum + c.delivered, 0);
  const opensUnique = campaigns.reduce((sum, c) => sum + c.opensUnique, 0);
  const clicksUnique = campaigns.reduce((sum, c) => sum + c.clicksUnique, 0);
  const conversions = campaigns.reduce((sum, c) => sum + c.conversions, 0);
  const conversionValue = campaigns.reduce(
    (sum, c) => sum + c.conversionValue,
    0,
  );

  return {
    campaignCount: campaigns.length,
    recipients,
    delivered,
    opensUnique,
    openRate: delivered > 0 ? opensUnique / delivered : 0,
    clicksUnique,
    clickRate: delivered > 0 ? clicksUnique / delivered : 0,
    conversions,
    conversionValue,
    revenuePerRecipient: recipients > 0 ? conversionValue / recipients : 0,
  };
}

export function getMockCampaignReport(): CampaignReport {
  const end = new Date();
  const start = subDays(end, 29);

  const campaigns: CampaignPerformance[] = [
    {
      id: "01JMOCKSPRING01",
      name: "Spring Edit · New Arrivals",
      channel: "email",
      status: "sent",
      sentAt: formatISO(subDays(end, 3)),
      recipients: 48210,
      delivered: 47102,
      opensUnique: 19842,
      openRate: 0.4213,
      clicksUnique: 4128,
      clickRate: 0.0876,
      clickToOpenRate: 0.208,
      conversions: 612,
      conversionRate: 0.013,
      conversionValue: 28450.2,
      revenuePerRecipient: 0.5901,
      unsubscribes: 96,
      unsubscribeRate: 0.002,
    },
    {
      id: "01JMOCKWINBACK02",
      name: "Winback · 30-day lapsed",
      channel: "email",
      status: "sent",
      sentAt: formatISO(subDays(end, 7)),
      recipients: 22140,
      delivered: 21688,
      opensUnique: 7420,
      openRate: 0.3421,
      clicksUnique: 1884,
      clickRate: 0.0869,
      clickToOpenRate: 0.254,
      conversions: 298,
      conversionRate: 0.0137,
      conversionValue: 16210.55,
      revenuePerRecipient: 0.7321,
      unsubscribes: 141,
      unsubscribeRate: 0.0065,
    },
    {
      id: "01JMOCKFLASH03",
      name: "Flash sale · 24 hours only",
      channel: "email",
      status: "sent",
      sentAt: formatISO(subDays(end, 11)),
      recipients: 61005,
      delivered: 59840,
      opensUnique: 27120,
      openRate: 0.4532,
      clicksUnique: 8120,
      clickRate: 0.1357,
      clickToOpenRate: 0.2994,
      conversions: 1240,
      conversionRate: 0.0207,
      conversionValue: 58220.0,
      revenuePerRecipient: 0.9544,
      unsubscribes: 188,
      unsubscribeRate: 0.0031,
    },
    {
      id: "01JMOCKSMS04",
      name: "SMS · Cart reminder",
      channel: "sms",
      status: "sent",
      sentAt: formatISO(subDays(end, 14)),
      recipients: 8420,
      delivered: 8310,
      opensUnique: 0,
      openRate: 0,
      clicksUnique: 1960,
      clickRate: 0.2359,
      clickToOpenRate: 0,
      conversions: 410,
      conversionRate: 0.0493,
      conversionValue: 19880.75,
      revenuePerRecipient: 2.3609,
      unsubscribes: 52,
      unsubscribeRate: 0.0063,
    },
    {
      id: "01JMOCKVIP05",
      name: "VIP early access · Fall drop",
      channel: "email",
      status: "sent",
      sentAt: formatISO(subDays(end, 18)),
      recipients: 12480,
      delivered: 12310,
      opensUnique: 6840,
      openRate: 0.5556,
      clicksUnique: 2210,
      clickRate: 0.1795,
      clickToOpenRate: 0.3231,
      conversions: 520,
      conversionRate: 0.0422,
      conversionValue: 41200.0,
      revenuePerRecipient: 3.3013,
      unsubscribes: 18,
      unsubscribeRate: 0.0015,
    },
    {
      id: "01JMOCKNEWS06",
      name: "Weekly newsletter · Style tips",
      channel: "email",
      status: "sent",
      sentAt: formatISO(subDays(end, 22)),
      recipients: 55320,
      delivered: 54110,
      opensUnique: 18240,
      openRate: 0.3371,
      clicksUnique: 2940,
      clickRate: 0.0543,
      clickToOpenRate: 0.1612,
      conversions: 186,
      conversionRate: 0.0034,
      conversionValue: 6840.4,
      revenuePerRecipient: 0.1237,
      unsubscribes: 210,
      unsubscribeRate: 0.0039,
    },
    {
      id: "01JMOCKRESTOCK07",
      name: "Restock alert · Best sellers",
      channel: "email",
      status: "sent",
      sentAt: formatISO(subDays(end, 26)),
      recipients: 18650,
      delivered: 18220,
      opensUnique: 9120,
      openRate: 0.5005,
      clicksUnique: 3480,
      clickRate: 0.191,
      clickToOpenRate: 0.3816,
      conversions: 640,
      conversionRate: 0.0351,
      conversionValue: 27650.9,
      revenuePerRecipient: 1.4826,
      unsubscribes: 44,
      unsubscribeRate: 0.0024,
    },
  ];

  return {
    source: "mock",
    timeframe: {
      key: "last_30_days",
      start: formatISO(start, { representation: "date" }),
      end: formatISO(end, { representation: "date" }),
    },
    accountName: "Demo Brand (sample data)",
    summary: summarize(campaigns),
    campaigns,
    message:
      "Showing sample campaign data. Authenticate Klaviyo with SSO in Cursor, then ask to pull last-30-day campaign performance.",
  };
}
